version: "3.8"
services:
  mongodb:
    image: mongo #mongo:4.4
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017